[package]
name = "eth2_ssz"
version = "0.1.0"
authors = ["Paul Hauner <paul@sigmaprime.io>"]
edition = "2018"
description = "SimpleSerialize (SSZ) as used in Ethereum 2.0"

[lib]
name = "ssz"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.2"
eth2_ssz_derive = { path = "../ssz_derive" }

[dependencies]
bytes = "0.4.9"
ethereum-types = "0.5"
hashing = { path = "../hashing" }
int_to_bytes = { path = "../int_to_bytes" }
hex = "0.3"
yaml-rust = "0.4"
